### ISSUE TITLE
Support for React 17?

### ISSUE THREAD

**Issue by carestad** [fakeheal/react-native-pan-pinch-view#1]
I am trying to install the package for my React Native (v0.67) project, but I am getting an error about the react depenceny as it seems to rely on React 16.x.x. Is it possible to adapt to React 17 and possibly 18 as well?

**Comment by carestad** [comment]
Woops. Seems to be mostly `npm` complaining about that. `yarn add react-native-pan-pinch-view` works though. But perhaps the `peerDependency` for react should be updated to support other major versions either way?

**Comment by Chronostyle** [comment]
had you fix it?i'm trying to change the peerDepedency but got error

**Comment by fakeheal** [comment]
Closed in 162710d05de1f30eed2796ca019b31648938d87a.
