### ISSUE TITLE
Are there any function that can return if the component hit the container edges, it returns a value like boolean?

### ISSUE THREAD

**Issue by Chronostyle** [fakeheal/react-native-pan-pinch-view#4]
how can i detect if an image had already hit the container edges? this can be useful in case of like this:

1. suppose you had a flatlist that has list of images and the flatlist's scrolled horizontally, scrollEnabled set to false when initialize
2. the image's component will be wrapped inside PanPinchView component and it should be on renderItem function

on this case flatlist scroll and pan gesture could be run on the same time, would be good if there's a function that can detect container edges so when it hit, a value is returned to control scrollEnabled's flatlist

**Comment by fakeheal** [comment]
Hi!

Thanks for taking the time to open this issue.

Would it be possible to provide a minimal reproducible example of your case? Maybe in expo?

There's no available method for your case, but I am willing to attempt implementing it alongside updating the library dependencies and making it available for React 17. That unfortunately will happen next week.

Best,
Ivanka

**Comment by fakeheal** [comment]
Closed in 162710d05de1f30eed2796ca019b31648938d87a. Demo can be found in the updated example app & information in the README.
