### ISSUE TITLE
Add rotation Feature

### ISSUE THREAD

**Issue by pooryamd** [fakeheal/react-native-pan-pinch-view#6]
Thank you for great module,
I am trying to add rotation functionality to rotate Image 90 degree and rotation works fine but panning function does not work fine.
Here is what I did: https://github.com/pooryamd/react-native-pan-pinch-view

Rotation works fine, but panning function is not; and I cannot figure it out.

**Comment by fakeheal** [comment]
Hi,

I am a little bit late, but if you're still in search of how to add rotation, I can help! 

Based on the code in your repository you want to add rotation by 90deg only? Or is it a starting point? Do you want to achieve rotating using the [Rotating gesture](https://docs.swmansion.com/react-native-gesture-handler/docs/gestures/rotation-gesture/)?

Thanks again for trying out the package! 🙌

**Comment by fakeheal** [comment]
I will close this issue due to inactivity. Feel free to reopen it.
