### ISSUE TITLE
Focal point not working on Android

### ISSUE THREAD

**Issue by surafelbm** [fakeheal/react-native-pan-pinch-view#8]
Hello, tried zooming in and out on Android but the zoom view flies away from under my fingers, this is working perfectly on iOS

**Comment by fakeheal** [comment]
Hi,

what version of the package are you using? Also what's your Android device/emulator (Android version) and RN version?

**Comment by fakeheal** [comment]
I will close this issue due to inactivity. Feel free to reopen it.

**Comment by hdjhdjhdj** [comment]
react-native-pan-pinch-view v2.0.0
RN v0.74.4
Installing APK 'app-debug.apk' on 'Redmi 8A - android10' for :app:debug
![image](https://github.com/user-attachments/assets/70303d91-0c0e-47a3-ae11-c02aebf74738)
![image](https://github.com/user-attachments/assets/d6fc8ca9-521f-43d5-b504-6679b40e3a70)

**Comment by hdjhdjhdj** [comment]
> Hi,
> 
> what version of the package are you using? Also what's your Android device/emulator (Android version) and RN version?

When zooming in on a picture with two fingers on an Android phone, the focus will be reset

**Comment by fakeheal** [comment]
Hey, @hdjhdjhdj,

can you also provide a screen recording of the issue? 🙏 

All the other information you added is super helpful, too!

Best,
Ivanka

**Comment by hdjhdjhdj** [comment]
https://github.com/user-attachments/assets/6c2b0685-6caf-4af4-9711-902839d87eb2

**Comment by fakeheal** [comment]
@hdjhdjhdj thank you for providing the video! ✨ 

Have you ran the examples provided in this repository? If you have, do you still experience this issue? If you haven't, can you run them and see if the package is the problem with this android version/device or if it's your specific implementation?

One suggestion I have from the code you shared is:
Have you tried setting the height of `containerDimensions` to the variable `height` (excluding the bottom navigation height & bar height)?

**Comment by hdjhdjhdj** [comment]
When the image magnification exceeds the set maxScale, this effect will be more pronounced.
I have tried other Android phones with the same effect

**Comment by hdjhdjhdj** [comment]
I'll run your demo and take a look。
My code is as follows
![image](https://github.com/user-attachments/assets/34af6669-17fc-4d8a-a7c3-5508362ce280)

**Comment by hdjhdjhdj** [comment]
The demo effect also has the same issue
https://github.com/user-attachments/assets/77619398-cecf-4296-bdde-e9420b941cf7
